apiVersion: v1
kind: Service
metadata:
  name: hedgehogdb-api
  namespace: hedgehogdb
  labels:
    app: hedgehogdb
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: hedgehogdb
