global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: hedgehog-local

scrape_configs:
  - job_name: "hedgehogdb"
    static_configs:
      # When HedgehogDB nodes run on the Docker host (3-, 10-, or 20-node cluster).
      - targets:
          - "host.docker.internal:8081"
          - "host.docker.internal:8082"
          - "host.docker.internal:8083"
          - "host.docker.internal:8084"
          - "host.docker.internal:8085"
          - "host.docker.internal:8086"
          - "host.docker.internal:8087"
          - "host.docker.internal:8088"
          - "host.docker.internal:8089"
          - "host.docker.internal:8090"
          - "host.docker.internal:8091"
          - "host.docker.internal:8092"
          - "host.docker.internal:8093"
          - "host.docker.internal:8094"
          - "host.docker.internal:8095"
          - "host.docker.internal:8096"
          - "host.docker.internal:8097"
          - "host.docker.internal:8098"
          - "host.docker.internal:8099"
          - "host.docker.internal:8100"
        labels:
          cluster: "hedgehog-local"
    metrics_path: "/metrics"
