apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hedgehogdb
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      external_labels:
        cluster: hedgehogdb-k8s
    scrape_configs:
      - job_name: hedgehogdb
        static_configs:
          - targets:
              - hedgehogdb-0.hedgehogdb.hedgehogdb.svc.cluster.local:8080
              - hedgehogdb-1.hedgehogdb.hedgehogdb.svc.cluster.local:8080
              - hedgehogdb-2.hedgehogdb.hedgehogdb.svc.cluster.local:8080
            labels:
              cluster: hedgehogdb-k8s
        metrics_path: /metrics
