apiVersion: v1
kind: Service
metadata:
  name: {{ include "hedgehogdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hedgehogdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: hedgehogdb
