apiVersion: v1
kind: Service
metadata:
  name: {{ include "hedgehogdb.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hedgehogdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: hedgehogdb
